# 데이터 가공

## 패키지 임포트

In [ ]:
# 넘파이와 판다스 라이브러리 가져오기
import numpy as np
import pandas as pd

In [70]:
# 데이터셋 불러오기

meteor_showers = pd.read_csv('data/meteorshowers.csv')
moon_phases_2026 = pd.read_csv('data/moon_phases_2026.csv')
cities = pd.read_csv('data/cities.csv')
constellations = pd.read_csv('data/constellations.csv')

In [87]:
# 유성우 데이터 확인하
meteor_showers

,name,radiant,bestmonth,startmonth,startday,endmonth,endday,hemisphere,preferredhemisphere
0,Lyrids,Lyra,april,april,21,april,22,northern,northern
1,Eta Aquarids,Aquarius,may,april,19,may,28,"northern, southern",southern
2,Orionids,Orion,october,october,2,november,7,"northern, southern","northern, southern"
3,Perseids,Perseus,august,july,14,august,24,northern,northern
4,Leonids,Leo,november,november,6,november,30,"northern, southern","northern, southern"

In [72]:
# 달의 위상 데이터 확인하기
moon_phases_2026

           date      moonphase  percentage specialevent
0    2026-01-01            NaN         NaN          NaN
1    2026-01-02            NaN         NaN          NaN
2    2026-01-03      Full Moon         1.0          NaN
3    2026-01-04            NaN         NaN          NaN
4    2026-01-05            NaN         NaN          NaN
..          ...            ...         ...          ...
360  2026-12-27            NaN         NaN          NaN
361  2026-12-28            NaN         NaN          NaN
362  2026-12-29            NaN         NaN          NaN
363  2026-12-30            NaN         NaN          NaN
364  2026-12-31  Third Quarter         0.5          NaN

[365 rows x 4 columns]

In [73]:
# 별자리 데이터 확인하기
constellations

  constellation bestmonth  latitudestart  latitudeend besttime hemisphere
0          Lyra    august             90          -40    21:00   northern
1      Aquarius   october             65          -90    21:00   southern
2         Orion   january             85          -75    21:00   northern
3       Perseus  december             90          -35    21:00   northern
4           Leo     april             90           65    21:00   northern

In [ ]:
# 도시 데이터 확인하기기
cities

                        city  latitude               country
0                  Abu Dhabi     24.47  United Arab Emirates
1                      Abuja      9.07               Nigeria
2                      Accra      5.55                 Ghana
3                  Adamstown    -25.07      Pitcairn Islands
4                Addis Ababa      9.02              Ethiopia
..                       ...       ...                   ...
251  Abidjan(former capital)      6.82           Ivory Coast
252                  Yaounde      3.87              Cameroon
253          Yaren(de facto)     -0.53                 Nauru
254                  Yerevan     40.18               Armenia
255                   Zagreb     45.82               Croatia

[256 rows x 3 columns]

In [83]:
# meteor_showers 유성우 정보 조회
meteor_showers.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   name                 5 non-null      str
 1   radiant              5 non-null      str
 2   bestmonth            5 non-null      str
 3   startmonth           5 non-null      str
 4   startday             5 non-null      int64
 5   endmonth             5 non-null      str
 6   endday               5 non-null      int64
 7   hemisphere           5 non-null      str
 8   preferredhemisphere  5 non-null      str
dtypes: int64(2), str(7)
memory usage: 778.0 bytes

## 컬럼 dtype 변경(월 이름)

In [84]:
# 유성우 월 이름 변경
# 월명을 숫자로 변환하기 위한 딕셔너리 생성 months
# 월명(영어 소문자)을 숫자로 매핑하는 딕셔너리
months = {
    'january': 1,
    'february': 2,
    'march': 3,
    'april': 4,
    'may': 5,
    'june': 6,
    'july': 7,
    'august': 8,
    'september': 9,
    'october': 10,
    'november': 11,
    'december': 12
}

In [85]:
# 유성우데이터프레임의 월명을 숫자로 변환 map 메소드 사용
meteor_showers['month'] = meteor_showers['month'].map(months)

KeyError: 'month'

In [78]:
# 유성우 월명이 숫자로 변경되었는지 정보 확인

In [79]:
# 다른 데이터프레임(달의위상, 별자리)도 월명을 숫자로 변환

In [80]:
constellations

  constellation bestmonth  latitudestart  latitudeend besttime hemisphere
0          Lyra    august             90          -40    21:00   northern
1      Aquarius   october             65          -90    21:00   southern
2         Orion   january             85          -75    21:00   northern
3       Perseus  december             90          -35    21:00   northern
4           Leo     april             90           65    21:00   northern

In [81]:
# 달의위상
moon_phases

NameError: name 'moon_phases' is not defined

In [ ]:
moon_phases.info()

In [ ]:
# 별자리
constellations

In [ ]:
constellations.info()

## 일자 정보 Datetime으로 변환(startdate 컬럼 생성)

In [ ]:
# 유성우 데이터프레임의 새로운 컬럼에 일자 정보를 datatime(20240428)으로 변환하여 저장, startdate, enddate
# startdate 컬럼 추가 20200428
# 2020, 4, 21 -> 20200421 -> 2020-04-28

In [ ]:
meteor_showers.info()

In [ ]:
# 유성우 데이터프레임의 새로운 컬럼에 일자 정보를 datatime(20240428)으로 변환하여 저장, startdate, enddate
# enddate 컬럼 추가

In [ ]:
moon_phases

In [ ]:
# moon_phases 데이터 프레임에 일자 정보를 datatime으로 변환하여 date컬럼 추가 20200428

In [ ]:
moon_phases.info()

## 달의 위상 데이터를 숫자로 변환

In [ ]:
# 달의 위상 데이터를 숫자로 변환하기

In [ ]:
# 달의위상 데이터프레임에 phases데이터를 이용하여 백분율 컬럼(percentage) 새롭게 추가하기
moon_phases['percentage'] = moon_phases['moonphase'].map(phase)
moon_phases

In [ ]:
moon_phases.sample(10)

## 불필요한 컬럼 삭제

In [ ]:
# 각 데이터 프레임에서 불필요한 컬럼 삭제하기

In [ ]:
constellations.drop(columns=['besttime'])
#안해도 문제없음
#데이터 출력확인후 대입
#constellations=constellations.drop(columns=['besttime'])

In [ ]:
meteor_showers.drop(columns=['startmonth','startday','endmonth','endday', 'preferredhemisphere'])
#안해도 문제없음
#데이터 출력확인후 대입
#meteor_showers = meteor_showers.drop(columns=['startmonth','startday','endmonth','endday', 'preferredhemisphere'])

In [ ]:
moon_phases

#month day moonphase specialevent 제거

In [ ]:
constellations
#추가작업없음

## 달의 위상 누락값 처리

In [ ]:
# 달의위상 데이터 프레임에서 percentage 컬럼의 결측치 처리하기
moon_phases['percentage'].ffill().fillna(0)

#ffill 이전값으로 데이터 채우기
#최초값은 이전값 없음으로 0으로채우기
# 대입하기
moon_phases['percentage'] = moon_phases['percentage'].ffill().fillna(0)

In [ ]:
moon_phases.info()

In [ ]:
moon_phases # 이전값으로 채워넣기!!

In [ ]:
moon_phases

In [ ]:
moon_phases.info()

# 데이터 분석

In [ ]:
도시의 위도를 확인
위도를 사용해서 해당 도시에 표시되는 별자리 확인
별자리를 사용해서 해당 도시에서 볼수 있는 유성우 확인
유성우를 사용해서 해당 유성우를 볼 수 있는 날짜 확인
날짜를 사용해서 달의 위상값이 가장 작은 최적 날짜 확인

마지막으로 사용자에게 기분좋은 문구 반환

## 위도 조회

In [ ]:
지정된 도시에서 각 유성우를 볼 수 있는 가능성이 높은 날짜를 예측하려고 합니다.

In [ ]:
# 도시 데이터프레임에서 검색한 열(검색한 도시의 위도)만 가져오기
# dframe.loc[조건, 가져올 컬럼 이름] 아래는 'Abu Dhabi'의 결과

cities
# 24.27

### 도시명 입력 후 위도 반환

In [ ]:
# 도시명을 입력하면 위도를 반환하는 함수 만들기

def predict_best_meteor_shower_viewing(city):
    
    return latitude

In [ ]:
print(predict_best_meteor_shower_viewing('Abu Dhabi'))

In [ ]:
print(predict_best_meteor_shower_viewing('Seoul'))

## 특정 위도에서 볼 수 있는 별자리 조회

In [ ]:
constellations

In [ ]:
# 24.47 혹은 37.55 위도값으로 관측 가능한 별자리 리스트를 반환
# ['Lyra','Aquarius','Orion', 'Perseus']

latitude = 37.55

In [ ]:
# 도시명을 입력하면 위도와 별자리 리스트를 반환하는 함수 만들기

def predict_best_meteor_shower_viewing(city):

    return latitude, constellations_list

In [ ]:
predict_best_meteor_shower_viewing('Busan')

In [ ]:
# 뉴질랜드 웰링턴으로 확인
predict_best_meteor_shower_viewing('Wellington')

In [ ]:
predict_best_meteor_shower_viewing('Seoul')

## 문자 안내 출력

In [ ]:
# 도시명을 입력히면 위도와 별자리리스트와 메시지를 반환하는 함수

def predict_best_meteor_shower_viewing(city):

    
    return latitude, constellations_list, meteor_shower_string

In [ ]:
predict_best_meteor_shower_viewing('Busan')

In [ ]:
wellington = predict_best_meteor_shower_viewing('Wellington')
wellington

## 유성우 관측 기간 조회(선택한 도시에서 관측 가능한 별자리 추출)

In [ ]:
meteor_showers.head()

In [ ]:
wellington

In [ ]:
# 유성우 관측 시작일 가져오기
# 여기서는 Wellington의 결과값을 가지고 조회

In [ ]:
# 유성우 관측 종료일

In [ ]:
# 별자리 근처 유성우 이름 추출

In [ ]:
# 여러 유성우 처리하기 및 유성우 근처 별자리 이름 가져오기

## 달의 위상 최저치 추출

In [ ]:
달 위상의 최소값(달에서 반사되는 빛의 최소량)을 찾을 수 있습니다. 이 예측 함수에서는 첫 번째 날짜만 확인합니다.

In [ ]:
# 가장 어두운 날 찾기
moon_phase_list['percentage'].idxmin() # 가장 백분율이 적은 행 인덱스 반환

In [ ]:
best_moon_date.to_pydatetime().strftime('%Y년 %m월 %d일')

In [ ]:
constellations

In [ ]:
meteor_showers

## 최적의 유성우 관측일

In [ ]:
# 도시명을 입력하면 관측가능한 유성우에 대한 정보를 알려주는 함수 작성하기

def predict_best_meteor_shower_viewing(city):
    
    return meteor_shower_string

In [ ]:
print(predict_best_meteor_shower_viewing('New York'))

In [ ]:
print(predict_best_meteor_shower_viewing('Wellington'))

In [ ]:
print(predict_best_meteor_shower_viewing('Seoul'))

In [ ]:
print(predict_best_meteor_shower_viewing('Abu Dhabi'))

# 항아 유성우 데이터 추가

In [ ]:
# 항아 유성우 데이터 추가하기
change_meteor_shower = {'name' : "Chang\'e", 'radiant' : 'Draco', 'bestmonth' : 'october', 'startmonth': 'october', 'startday' : 1,
                        'endmonth' : 'october', 'endday' : 31, 'hemisphere' : 'northern', 'preferredhemisphere' : 'northern' }
change_meteor_shower_df = pd.DataFrame(change_meteor_shower,index = [0])
change_meteor_shower_df

In [ ]:
# meteorshowers.csv 파일 읽어와서 new_meteor_showers 변수에 저장
new_meteor_showers = pd.read_csv('data/meteorshowers.csv')
new_meteor_showers

In [ ]:
# new_meteor_showers 데이터프레임에 change_meteor_shower_df 데이터프레임 추가하기 concat
new_meteor_showers = pd.concat([new_meteor_showers, change_meteor_shower_df], ignore_index=True)
new_meteor_showers

In [ ]:
# Chang'e 유성우에 대해 Draconids 유성우가 10월 초에 발생할 가능성이 높은 용자리를 선택합니다. 이 유성우를 가상 유성우의 참조로 사용
# 용자리 항목 추가하기기
draco_constellation = {'constellation' : 'Draco', 'bestmonth' : 'july', 'latitudestart' : 90, 'latitudeend' : -15, 'besttime' :2100, 'hemisphere' : 'northern'}
draco_constellation_df = pd.DataFrame(draco_constellation, index = [0])
draco_constellation_df

In [ ]:
# 별자리 파일 읽어와서 new_constellations에 저장하기
new_constellations = pd.read_csv('data/constellations.csv')
new_constellations

In [ ]:
# new_constellations 데이터프레임에 draco_constellation_df 추가하기 concat
new_constellations =  pd.concat([new_constellations, draco_constellation_df], ignore_index=True)# Todo Here
new_constellations

In [ ]:
# new_meteor_showers 데이터프레임 월명 매핑
new_meteor_showers['startmonth'] = new_meteor_showers['startmonth'].map(months)
new_meteor_showers['bestmonth'] = new_meteor_showers['bestmonth'].map(months)
new_meteor_showers['endmonth'] = new_meteor_showers['endmonth'].map(months)
new_meteor_showers

In [ ]:
# new_constellations 데이터프레임 월명 매핑
new_constellations['bestmonth'] = new_constellations['bestmonth'].map(months)
new_constellations

In [ ]:
# new_meteor_showers 날짜형식 바꿔서 새로운 컬럼으로 추가 startdate, enddate
new_meteor_showers['startdate'] = pd.to_datetime(2020 * 10000 + 
                                             new_meteor_showers['startmonth'] * 100 + 
                                             new_meteor_showers['startday'],
                                             format = '%Y%m%d')
new_meteor_showers['enddate'] = pd.to_datetime(2020 * 10000 + 
                                             new_meteor_showers['endmonth'] * 100 + 
                                             new_meteor_showers['endday'],
                                             format = '%Y%m%d')

new_meteor_showers

In [ ]:
# 도시명을 입력히면 위도를 반환하는 함수
def predict_best_meteor_shower_viewing(city):


    return meteor_shower_string

In [ ]:
print(predict_best_meteor_shower_viewing('Beijing'))